#ifndef INCLUDED_DEFINE_H
#define INCLUDED_DEFINE_H

#define CHAR_NAME_MAX 50
#define CHAR_TYPE_MAX 20
#define CHAR_DESC_MAX 200
#define LINE_LOG_MAX	10
#define COUT_HP_FOUILLE 2
#define COEFF_VENTE 0.9

#endif
